# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Automatic update checking
  config.vm.box_check_update = true

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory and # of cpus on the VM:
    vb.memory = 4096
    vb.cpus = 4
  end

  # The template folder contains the keystore that is used for signing jgraphx-demo.jar as well as GIT_USERNAME and GIT_EMAIL
  config.vm.synced_folder "./template", "/opt/system/template"

  # Provision Settings
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade
    apt-get install -y ant default-jdk git maven
    grep -q JAVA_HOME /etc/environment || echo 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"' >> /etc/environment
    mkdir -p /home/vagrant/.m2
    chown vagrant:vagrant /home/vagrant/.m2
    cp /opt/system/template/settings.xml /home/vagrant/.m2/settings.xml
  SHELL
end
